##
##  Makefile -- Build procedure for sample ifdefine_extended Apache module
##  Autogenerated via ``apxs -n ifdefine_extended -g''.
##

builddir=.
top_srcdir=/Users/hiroya/local/httpd-2.0.63
top_builddir=/Users/hiroya/local/httpd-2.0.63
include /Users/hiroya/local/httpd-2.0.63/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_ifdefine_extended.o mod_ifdefine_extended.lo mod_ifdefine_extended.slo mod_ifdefine_extended.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/ifdefine_extended

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

tidy:
	indent -i4 -npsl -di0 -br -nce -d0 -cli0 -npcs -nfc1 -nut *.c